apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-deployment
  labels:
    app.kubernetes.io/name: read-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: read-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: read-app
      annotations:  
        dapr.io/app-id: read-app
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
    spec:
      containers:
      - name: read-app
        image: ko://github.com/salaboy/read-values
        env: 
        - name: STATE_STORE_NAME
          value: statestore
        ports: 
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/liveness
            port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: read-app-service
spec:
  selector:
    app.kubernetes.io/name: read-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080