apiVersion: apps/v1
kind: Deployment
metadata:
  name: write-deployment
  labels:
    app.kubernetes.io/name: write-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: write-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: write-app
      annotations:  
        dapr.io/app-id: write-app
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/volume-mounts: "wasm-volume:/mnt/wasm"
        dapr.io/log-level: "debug"
        dapr.io/config: "appconfig"
    spec:
      volumes:
        - name: wasm-volume
          configMap:
            name: wasm-router
            items:
              - key: filter.wasm
                path: filter.wasm
      containers:
      - name: write-app
        image: ko://github.com/salaboy/kubecon-eu-2023/write-values
        volumeMounts: 
          - name: wasm-volume
            mountPath: /mnt/wasm
        env: 
        - name: STATE_STORE_NAME
          value: statestore
        ports: 
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/liveness
            port: 8080