apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app.kubernetes.io/name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend-app
      annotations:  
        dapr.io/app-id: frontend-app
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"  
    spec:
      containers:
      - name: frontend-app
        image: ko://github.com/salaboy/kubecon-eu-2023/frontend
        ports: 
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/liveness
            port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
spec:
  selector:
    app.kubernetes.io/name: frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080