apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  labels:
    app.kubernetes.io/name: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-app
      annotations:  
        dapr.io/app-id: read-app
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
    spec:
      containers:
      - name: java-app
        image: docker.io/salaboy/dapr-java-app
        env: 
        - name: STATE_STORE_NAME
          value: statestore
        ports: 
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app.kubernetes.io/name: java-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  labels:
    app.kubernetes.io/name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-app
      annotations:  
        dapr.io/app-id: write-app
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
    spec:
      containers:
      - name: go-app
        image: docker.io/salaboy/go-app-1c03bcf417fa9388537cc9412c9e168b@sha256:f1e4e616a9af6364871dc02ecf9403e043fe8cbe8253e01a83066ff4d68f44ba
        env: 
        - name: STATE_STORE_NAME
          value: statestore
        ports: 
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  selector:
    app.kubernetes.io/name: go-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080

---

## Subcriber    

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subcriber-deployment
  labels:
    app.kubernetes.io/name: subcriber-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: subcriber-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: subcriber-app
      annotations:  
        dapr.io/app-id: subcriber-app
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
    spec:
      containers:
      - name: subcriber-app
        image: docker.io/salaboy/subscriber-4a906ae149426dec3141b6935e4b8e2d
        ports: 
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: subcriber-service
spec:
  selector:
    app.kubernetes.io/name: subcriber-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080